/* =====================================================
   TECNOCEL - CATÁLOGO REAL
   Generado desde: CATALOGO MAYORISTA - KING SMART.xlsx
   Margen aplicado: +20% sobre los precios del catálogo.
   Los productos sin precio quedan como "Consultar".
===================================================== */

const products = [
  {
    "id": 1,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 2,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 11 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 3,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 11 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 4,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 12/12 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 5,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 12MINI",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 6,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 12 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 7,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 13MINI",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 8,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 9,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 10,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 11,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 12,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 14PLUS",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 13,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 14,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 15,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 16,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 15PLUS",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 17,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 18,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 19,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 20,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 16E",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 21,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 22,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 23,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 24,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 25,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 26,
    "name": "FUNDA MAGSAFE CLEAR CASE",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 2646.0,
    "priceUSD": 1.68,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 27,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 28,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 11 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 29,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 11 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 30,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 31,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 12MINI",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 32,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 12 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 33,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 12 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 34,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 35,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 13MINI",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 36,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 37,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 38,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 39,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 14PLUS",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 40,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 41,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 42,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 43,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 15PLUS",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 44,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 45,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 46,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 47,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 16E",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 48,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 49,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 50,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 51,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 52,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 53,
    "name": "FUNDA ANTISHOCK TRANSPARENTE",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 1228.5,
    "priceUSD": 0.78,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 54,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 55,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 11 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 56,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 11 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 57,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 58,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 12 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 59,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 12 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 60,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 61,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 62,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 63,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 64,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 65,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 66,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 67,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 68,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 69,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 70,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 71,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 72,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 73,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 74,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 75,
    "name": "FUNDA MAGSAFE DIAMOND",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 76,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 77,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 78,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 79,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 80,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 81,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 82,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 83,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 84,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 85,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 86,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 87,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 88,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 89,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 90,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 91,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 92,
    "name": "FUNDA MAGSAFE ELECTRO PLATED",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 3591.0,
    "priceUSD": 2.28,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 93,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 94,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 95,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 96,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 97,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 98,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 99,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 100,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 101,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 102,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 103,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 104,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 105,
    "name": "FUNDA DISNEY MICKEY MOUSE",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 106,
    "name": "FUNDA CEREZA",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 107,
    "name": "FUNDA CEREZA",
    "detail": "IPH 12PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 108,
    "name": "FUNDA CEREZA",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 109,
    "name": "FUNDA CEREZA",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 110,
    "name": "FUNDA CEREZA",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 111,
    "name": "FUNDA CEREZA",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 112,
    "name": "FUNDA CEREZA",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 113,
    "name": "FUNDA CEREZA",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 114,
    "name": "FUNDA CEREZA",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 115,
    "name": "FUNDA CEREZA",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 116,
    "name": "FUNDA CEREZA",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 117,
    "name": "FUNDA CEREZA",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 118,
    "name": "FUNDA CEREZA",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 119,
    "name": "FUNDA CEREZA",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 120,
    "name": "FUNDA CEREZA",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 121,
    "name": "FUNDA CEREZA",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 122,
    "name": "FUNDA CEREZA",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 4914.0,
    "priceUSD": 3.12,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 123,
    "name": "FUNDA MOÑO",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 124,
    "name": "FUNDA MOÑO",
    "detail": "IPH 12PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 125,
    "name": "FUNDA MOÑO",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 126,
    "name": "FUNDA MOÑO",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 127,
    "name": "FUNDA MOÑO",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 128,
    "name": "FUNDA MOÑO",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 129,
    "name": "FUNDA MOÑO",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 130,
    "name": "FUNDA MOÑO",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 131,
    "name": "FUNDA MOÑO",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 132,
    "name": "FUNDA MOÑO",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 133,
    "name": "FUNDA MOÑO",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 134,
    "name": "FUNDA MOÑO",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 135,
    "name": "FUNDA MOÑO",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 136,
    "name": "FUNDA MOÑO",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 137,
    "name": "FUNDA MOÑO",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 138,
    "name": "FUNDA MOÑO",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 139,
    "name": "FUNDA MOÑO",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 140,
    "name": "FUNDA MOÑO",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 3024.0,
    "priceUSD": 1.92,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 141,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 142,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 12PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 143,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 144,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 145,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 146,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 147,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 148,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 149,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 150,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 151,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 152,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 153,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 16E",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 154,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 155,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 156,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 157,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 158,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 159,
    "name": "FUNDA MARGARITA CON RESINA",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 6615.0,
    "priceUSD": 4.2,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 160,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 161,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 162,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 163,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 164,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 165,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 166,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 167,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 168,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 169,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 170,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 171,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 172,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 173,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 17AIR",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 174,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 175,
    "name": "FUNDA MAGSAFE FLORES CON RESINA",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 8505.0,
    "priceUSD": 5.4,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 176,
    "name": "FUNDA GOKU",
    "detail": "IPH 11",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 177,
    "name": "FUNDA GOKU",
    "detail": "IPH 12",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 178,
    "name": "FUNDA GOKU",
    "detail": "IPH 12 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 179,
    "name": "FUNDA GOKU",
    "detail": "IPH 13",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 180,
    "name": "FUNDA GOKU",
    "detail": "IPH 13 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 181,
    "name": "FUNDA GOKU",
    "detail": "IPH 13 PRO MAX",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 182,
    "name": "FUNDA GOKU",
    "detail": "IPH 14",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 183,
    "name": "FUNDA GOKU",
    "detail": "IPH 14 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 184,
    "name": "FUNDA GOKU",
    "detail": "IPH 14 PRO MAX",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 185,
    "name": "FUNDA GOKU",
    "detail": "IPH 15",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 186,
    "name": "FUNDA GOKU",
    "detail": "IPH 15 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 187,
    "name": "FUNDA GOKU",
    "detail": "IPH 15 PRO MAX",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 188,
    "name": "FUNDA GOKU",
    "detail": "IPH 16",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 189,
    "name": "FUNDA GOKU",
    "detail": "IPH 16 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 190,
    "name": "FUNDA GOKU",
    "detail": "IPH 16 PRO MAX",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 191,
    "name": "FUNDA GOKU",
    "detail": "IPH 17",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 192,
    "name": "FUNDA GOKU",
    "detail": "IPH 17 PRO",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 193,
    "name": "FUNDA GOKU",
    "detail": "IPH 17 PRO MAX",
    "category": "Fundas",
    "price": 2835.0,
    "priceUSD": 1.8,
    "stock": true,
    "comment": "",
    "icon": "📱"
  },
  {
    "id": 194,
    "name": "TEMPLADO 9D",
    "detail": "IPH XR/11",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 195,
    "name": "TEMPLADO 9D",
    "detail": "IPH X/XS/11 PRO",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 196,
    "name": "TEMPLADO 9D",
    "detail": "IPH XS MAX/11 PRO MAX",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 197,
    "name": "TEMPLADO 9D",
    "detail": "IPH 12/12 PRO",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 198,
    "name": "TEMPLADO 9D",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 199,
    "name": "TEMPLADO 9D",
    "detail": "IPH 13/13 PRO/14",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 200,
    "name": "TEMPLADO 9D",
    "detail": "IPH 13 PRO MAX/14PLUS",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 201,
    "name": "TEMPLADO 9D",
    "detail": "IPH 14 PRO",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 202,
    "name": "TEMPLADO 9D",
    "detail": "IPH 14 PRO MAX",
    "category": "Templados",
    "price": 699.3,
    "priceUSD": 0.44,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 203,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH XR/11",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 204,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH X/XS/11 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 205,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH XS MAX/11 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 206,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 12/12 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 207,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 208,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 13/13 PRO/14",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 209,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 13 PRO MAX/14PLUS",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 210,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 14 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 211,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 14 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 212,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 15",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 213,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 15 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 214,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 15 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 215,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 16",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 216,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 16 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 217,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 16 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 218,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 17AIR",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 219,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 17",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 220,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 17 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 221,
    "name": "TEMPLADO - GORILLA GLASS",
    "detail": "IPH 17 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 222,
    "name": "TEMPLADO MATTE",
    "detail": "IPH XR/11",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 223,
    "name": "TEMPLADO MATTE",
    "detail": "IPH X/XS/11 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 224,
    "name": "TEMPLADO MATTE",
    "detail": "IPH XS MAX/11 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 225,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 12/12 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 226,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 227,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 13/13 PRO/14",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 228,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 13 PRO MAX/14PLUS",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 229,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 14 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 230,
    "name": "TEMPLADO MATTE",
    "detail": "IPH 14 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 231,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 15",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 232,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 15 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 233,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 15 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 234,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 16",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 235,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 16 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 236,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 16 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 237,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 17",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 238,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 17AIR",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 239,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 17 PRO",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 240,
    "name": "TEMPLADO MATTE - GORILLA GLASS",
    "detail": "IPH 17 PRO MAX",
    "category": "Templados",
    "price": 1701.0,
    "priceUSD": 1.08,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 241,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH XR/11",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 242,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH X/XS/11 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 243,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH XS MAX/11 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 244,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 12/12 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 245,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 246,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 13/13 PRO/14",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 247,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 13 PRO MAX/14PLUS",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 248,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 14 PRO",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 249,
    "name": "TEMPLADO ANTI ESPIA",
    "detail": "IPH 14 PRO MAX",
    "category": "Templados",
    "price": 1323.0,
    "priceUSD": 0.84,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 250,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 15",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 251,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 15 PRO",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 252,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 15 PRO MAX",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 253,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 16",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 254,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 16 PRO",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 255,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 16 PRO MAX",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 256,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 17",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 257,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 17AIR",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 258,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 17 PRO",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 259,
    "name": "TEMPLADO ANTI ESPIA - GORILLA GLASS",
    "detail": "IPH 17 PRO MAX",
    "category": "Templados",
    "price": 1890.0,
    "priceUSD": 1.2,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 260,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 11/12/12MINI",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 261,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 11 PRO/11 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 262,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 12 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 263,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 264,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 13 /13 MINI",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 265,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 13 PRO/13 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 266,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 14/14 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 267,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 14 PRO/14 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 268,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 15/15 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 269,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 15 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 270,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 15 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 271,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD/PINK",
    "detail": "IPH 16/16 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 272,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD",
    "detail": "IPH 16 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 273,
    "name": "PROTECTOR DE CAMARA DIAMANTE - SILVER/GOLD",
    "detail": "IPH 16 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 274,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER",
    "detail": "IPH 11/12/12MINI",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 275,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER",
    "detail": "IPH 11 PRO/11 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 276,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/BLUE",
    "detail": "IPH 12 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 277,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/BLUE",
    "detail": "IPH 12 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 278,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/BLUE",
    "detail": "IPH 13 /13 MINI",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 279,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/BLUE",
    "detail": "IPH 13 PRO/13 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 280,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/BLUE/PINK",
    "detail": "IPH 14/14 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 281,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/PINK",
    "detail": "IPH 14 PRO/14 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 282,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER/PINK",
    "detail": "IPH 15/15 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 283,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER",
    "detail": "IPH 15 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 284,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/GOLD/SILVER",
    "detail": "IPH 15 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 285,
    "name": "PROTECTOR DE CAMARA COLOR - BLACK/SILVER/BLUE/GREEN/PINK",
    "detail": "IPH 16/16 PLUS",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 286,
    "name": "PROTECTOR DE CAMARA COLOR - BROWN/SPACE GRAY/BLACK/SILVER",
    "detail": "IPH 16 PRO",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 287,
    "name": "PROTECTOR DE CAMARA COLOR - BROWN/SPACE GRAY/BLACK/SILVER",
    "detail": "IPH 16 PRO MAX",
    "category": "Templados",
    "price": 1247.4,
    "priceUSD": 0.79,
    "stock": true,
    "comment": "",
    "icon": "🛡️"
  },
  {
    "id": 288,
    "name": "PROTECTOR DE CARGADOR 20W - APPLE",
    "detail": "",
    "category": "Accesorios",
    "price": 4025.7,
    "priceUSD": 2.56,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 289,
    "name": "COME CABLE",
    "detail": "",
    "category": "Accesorios",
    "price": 1549.8,
    "priceUSD": 0.98,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 290,
    "name": "MALLA APPLE WATCH",
    "detail": "",
    "category": "Accesorios",
    "price": null,
    "priceUSD": null,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "⚡"
  },
  {
    "id": 291,
    "name": "PROTECTORES AIRPODS 1/2",
    "detail": "",
    "category": "Accesorios",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 292,
    "name": "PROTECTORES AIRPODS PRO",
    "detail": "",
    "category": "Accesorios",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 293,
    "name": "PROTECTORES AIRPODS 3",
    "detail": "",
    "category": "Accesorios",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 294,
    "name": "PROTECTORES AIRPODS PRO 2",
    "detail": "",
    "category": "Accesorios",
    "price": 4536.0,
    "priceUSD": 2.88,
    "stock": true,
    "comment": "",
    "icon": "⚡"
  },
  {
    "id": 295,
    "name": "PROTECTORES AIRPODS 4",
    "detail": "",
    "category": "Accesorios",
    "price": null,
    "priceUSD": null,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "⚡"
  },
  {
    "id": 296,
    "name": "CABEZAL 20W - CON CAJA\n\nCALIDAD ORIGINAL\n\nPATA RECTA",
    "detail": "",
    "category": "Cargadores",
    "price": 35910.0,
    "priceUSD": 22.8,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 297,
    "name": "CABEZAL 20W - CON CAJA\n\nCALIDAD SIMIL ORIGINAL\n\nPATA RECTA",
    "detail": "",
    "category": "Cargadores",
    "price": 17010.0,
    "priceUSD": 10.8,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 298,
    "name": "CABEZAL 20W - CON CAJA\n\nCALIDAD AAAA\n\nPATA RECTA",
    "detail": "",
    "category": "Cargadores",
    "price": 9922.5,
    "priceUSD": 6.3,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 299,
    "name": "CABEZAL 5W FOXCONN - CON CAJA\n\nCALIDAD ORIGINAL\n\nPATA RECTA",
    "detail": "",
    "category": "Cargadores",
    "price": 15120.0,
    "priceUSD": 9.6,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔌"
  },
  {
    "id": 300,
    "name": "CABEZAL 5W FOXCONN - SIN CAJA\n\nCALIDAD HIGH COPY\n\nPATA RECTA",
    "detail": "",
    "category": "Cargadores",
    "price": 5008.5,
    "priceUSD": 3.18,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 301,
    "name": "CABLE - USB A LIGHTNING -  CON CAJA\n\nORIGINAL",
    "detail": "",
    "category": "Cargadores",
    "price": 13230.0,
    "priceUSD": 8.4,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔌"
  },
  {
    "id": 302,
    "name": "CABLE FOXCONN 1M - USB A LIGHTNING  - SIN CAJA\n\nCALIDAD AAAA",
    "detail": "",
    "category": "Cargadores",
    "price": 2872.8,
    "priceUSD": 1.82,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 303,
    "name": "CABLE - USB C A LIGHTNING -  CON CAJA\n\nORIGINAL",
    "detail": "",
    "category": "Cargadores",
    "price": 13608.0,
    "priceUSD": 8.64,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 304,
    "name": "CABLE FOXCONN 1M - USB C A LIGHTNING  - SIN CAJA\n\nCALIDAD AAAA",
    "detail": "",
    "category": "Cargadores",
    "price": 3402.0,
    "priceUSD": 2.16,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 305,
    "name": "CABLE - C A C -  CON CAJA\n\nORIGINAL",
    "detail": "",
    "category": "Cargadores",
    "price": 16065.0,
    "priceUSD": 10.2,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 306,
    "name": "CABLE FOXCONN 1M - C A C  - SIN CAJA\n\nCALIDAD AAAA",
    "detail": "",
    "category": "Cargadores",
    "price": 3685.5,
    "priceUSD": 2.34,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 307,
    "name": "BATTERY PACK APPLE - PREMIUM (5.000 mAh)",
    "detail": "",
    "category": "Cargadores",
    "price": 15120.0,
    "priceUSD": 9.6,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 308,
    "name": "BATTERY PACK APPLE - PREMIUM (10.000 mAh)",
    "detail": "",
    "category": "Cargadores",
    "price": 17955.0,
    "priceUSD": 11.4,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 309,
    "name": "CARGADOR MAGSAFE APPLE - PREMIUM",
    "detail": "",
    "category": "Cargadores",
    "price": 12285.0,
    "priceUSD": 7.8,
    "stock": true,
    "comment": "",
    "icon": "🔌"
  },
  {
    "id": 310,
    "name": "IPAD 11 GEN 128 GB - SOLO WIFI",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 897750.0,
    "priceUSD": 570.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 311,
    "name": "IPAD AIR M4  - 128 GB - SOLO WIFI",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 1313550.0,
    "priceUSD": 834.0,
    "stock": false,
    "comment": "SIN STOCK ESPERANDO INGRESO",
    "icon": ""
  },
  {
    "id": 312,
    "name": "MACBOOK NEO 13¨ - 8/256 GB",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 1483650.0,
    "priceUSD": 942.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 313,
    "name": "MACBOOK NEO 13¨ - 8/512 GB",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 1672650.0,
    "priceUSD": 1062.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 314,
    "name": "MACBOOK AIR M5 13¨ - 16/512 GB",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 2457000.0,
    "priceUSD": 1560.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 315,
    "name": "MACBOOK AIR M5 15¨ - 16/512 GB",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 2872800.0,
    "priceUSD": 1824.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 316,
    "name": "APPLE WATCH S11 42 MM",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 680400.0,
    "priceUSD": 432.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 317,
    "name": "APPLE WATCH S11 46 MM",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 746550.0,
    "priceUSD": 474.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 318,
    "name": "APPLE WATCH ULTRA 3 -  49 MM + CELL",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 1436400.0,
    "priceUSD": 912.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 319,
    "name": "APPLE AIRTAGS PACK X4 - PRECIO UNITARIO",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 66150.0,
    "priceUSD": 42.0,
    "stock": false,
    "comment": "SIN STOCK ESPERANDO INGRESO",
    "icon": ""
  },
  {
    "id": 320,
    "name": "APPLE MAGIC MOUSE",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 217350.0,
    "priceUSD": 138.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 321,
    "name": "APPLE PENCIL USB - C",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 198450.0,
    "priceUSD": 126.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 322,
    "name": "APPLE PENCIL PRO",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 255150.0,
    "priceUSD": 162.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 323,
    "name": "APPLE AIRPODS 4",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 255150.0,
    "priceUSD": 162.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 324,
    "name": "APPLE AIRPODS 4 - CON CANCELACION",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 330750.0,
    "priceUSD": 210.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 325,
    "name": "AIRPODS PRO 3",
    "detail": "ORIGINAL",
    "category": "Apple",
    "price": 463050.0,
    "priceUSD": 294.0,
    "stock": true,
    "comment": "",
    "icon": ""
  },
  {
    "id": 326,
    "name": "AIRPODS PRO 2GEN - PREMIUM",
    "detail": "",
    "category": "Auriculares",
    "price": 18900.0,
    "priceUSD": 12.0,
    "stock": true,
    "comment": "",
    "icon": "🎧"
  },
  {
    "id": 327,
    "name": "ADAPATADOR AMERICANO PATA OBLICUA",
    "detail": "",
    "category": "Artículos",
    "price": 623.7,
    "priceUSD": 0.4,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 328,
    "name": "SOPORTE PARA CELULAR\nADHESIVO / PARED",
    "detail": "",
    "category": "Artículos",
    "price": 756.0,
    "priceUSD": 0.48,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 329,
    "name": "SONY - PS5 SLIM 1 TB - DIGITAL - CALL OF DUTY BLACK OPS 6",
    "detail": "",
    "category": "Artículos",
    "price": 992250.0,
    "priceUSD": 630.0,
    "stock": false,
    "comment": "SIN STOCK ESPERANDO INGRESO",
    "icon": "📦"
  },
  {
    "id": 330,
    "name": "SONY - JOYSTICK PS5",
    "detail": "ORIGINAL",
    "category": "Artículos",
    "price": 164430.0,
    "priceUSD": 104.4,
    "stock": false,
    "comment": "SIN STOCK ESPERANDO INGRESO",
    "icon": "📦"
  },
  {
    "id": 331,
    "name": "JBL FLIP 6",
    "detail": "ORIGINAL",
    "category": "Artículos",
    "price": 187110.0,
    "priceUSD": 118.8,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 332,
    "name": "JBL GO 4",
    "detail": "ORIGINAL",
    "category": "Artículos",
    "price": 98280.0,
    "priceUSD": 62.4,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 333,
    "name": "JBL GO ESSENTIAL",
    "detail": "ORIGINAL",
    "category": "Artículos",
    "price": 75600.0,
    "priceUSD": 48.0,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 334,
    "name": "ROKU PREMIERE - 4K",
    "detail": "ORIGINAL",
    "category": "Artículos",
    "price": 68985.0,
    "priceUSD": 43.8,
    "stock": true,
    "comment": "",
    "icon": "📦"
  },
  {
    "id": 335,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE XR",
    "detail": "",
    "category": "Repuestos",
    "price": 29295.0,
    "priceUSD": 18.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 336,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE XS",
    "detail": "",
    "category": "Repuestos",
    "price": 32130.0,
    "priceUSD": 20.4,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 337,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE XS MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 39690.0,
    "priceUSD": 25.2,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 338,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 11",
    "detail": "",
    "category": "Repuestos",
    "price": 29295.0,
    "priceUSD": 18.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 339,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE SE2",
    "detail": "",
    "category": "Repuestos",
    "price": 26460.0,
    "priceUSD": 16.8,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 340,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 11 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 35910.0,
    "priceUSD": 22.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 341,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 11 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 39690.0,
    "priceUSD": 25.2,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 342,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 12 / 12 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 30240.0,
    "priceUSD": 19.2,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 343,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 12 MINI",
    "detail": "",
    "category": "Repuestos",
    "price": 26460.0,
    "priceUSD": 16.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 344,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 12 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 39690.0,
    "priceUSD": 25.2,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 345,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 13",
    "detail": "",
    "category": "Repuestos",
    "price": 34020.0,
    "priceUSD": 21.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 346,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 13 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 42525.0,
    "priceUSD": 27.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 347,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 13 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 45360.0,
    "priceUSD": 28.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 348,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 14",
    "detail": "",
    "category": "Repuestos",
    "price": 34020.0,
    "priceUSD": 21.6,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 349,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 14 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 43470.0,
    "priceUSD": 27.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 350,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 14 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 54810.0,
    "priceUSD": 34.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 351,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 15",
    "detail": "",
    "category": "Repuestos",
    "price": 37800.0,
    "priceUSD": 24.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 352,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 15 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 47250.0,
    "priceUSD": 30.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 353,
    "name": "BATERIA AMPSENTRIX CORE - IPHONE 15 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 54810.0,
    "priceUSD": 34.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 354,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 12 / 12 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 40635.0,
    "priceUSD": 25.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 355,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 12 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 50085.0,
    "priceUSD": 31.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 356,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 13",
    "detail": "",
    "category": "Repuestos",
    "price": 44982.0,
    "priceUSD": 28.56,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 357,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 13 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 44793.0,
    "priceUSD": 28.44,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 358,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 13 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 51408.0,
    "priceUSD": 32.64,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 359,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 14",
    "detail": "",
    "category": "Repuestos",
    "price": 46305.0,
    "priceUSD": 29.4,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 360,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 14 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 50085.0,
    "priceUSD": 31.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 361,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 14 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 52920.0,
    "priceUSD": 33.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 362,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 15",
    "detail": "",
    "category": "Repuestos",
    "price": 46305.0,
    "priceUSD": 29.4,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 363,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 15 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 50463.0,
    "priceUSD": 32.04,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 364,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 15 PLUS",
    "detail": "",
    "category": "Repuestos",
    "price": 48762.0,
    "priceUSD": 30.96,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 365,
    "name": "BATERIA AMPSENTRIX PLUS - IPHONE 15 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 58590.0,
    "priceUSD": 37.2,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 366,
    "name": "PANTALLA INCELL+ - IPHONE 8",
    "detail": "",
    "category": "Repuestos",
    "price": 37800.0,
    "priceUSD": 24.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 367,
    "name": "PANTALLA INCELL+ - IPHONE 8 PLUS",
    "detail": "",
    "category": "Repuestos",
    "price": 52920.0,
    "priceUSD": 33.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 368,
    "name": "PANTALLA SOFT OLED - IPHONE X",
    "detail": "",
    "category": "Repuestos",
    "price": 137970.0,
    "priceUSD": 87.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 369,
    "name": "PANTALLA SOFT OLED - IPHONE XS",
    "detail": "",
    "category": "Repuestos",
    "price": 137970.0,
    "priceUSD": 87.6,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 370,
    "name": "PANTALLA INCELL - IPHONE XR",
    "detail": "",
    "category": "Repuestos",
    "price": 56700.0,
    "priceUSD": 36.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 371,
    "name": "PANTALLA INCELL+ - IPHONE 11 (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 56700.0,
    "priceUSD": 36.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 372,
    "name": "PANTALLA SOFT OLED - IPHONE 11 PRO (ADMITE TRANSPLANTE IC) - GX",
    "detail": "",
    "category": "Repuestos",
    "price": null,
    "priceUSD": null,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 373,
    "name": "PANTALLA SOFT OLED - IPHONE 11 PRO MAX (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": null,
    "priceUSD": null,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 374,
    "name": "PANTALLA SOFT OLED - IPHONE 11 PRO MAX (NO ADMITE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": null,
    "priceUSD": null,
    "stock": false,
    "comment": "SIN STOCK - ESPERANDO INGRESO",
    "icon": "🔧"
  },
  {
    "id": 375,
    "name": "PANTALLA HARD OLED - IPHONE 12 / 12 PRO (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 103950.0,
    "priceUSD": 66.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 376,
    "name": "PANTALLA SOFT OLED - IPHONE 12 / 12 PRO (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 151200.0,
    "priceUSD": 96.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 377,
    "name": "PANTALLA HARD OLED - IPHONE 12 / 12 PRO (NO ADMITE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 122850.0,
    "priceUSD": 78.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 378,
    "name": "PANTALLA SOFT OLED - IPHONE 12 PRO MAX (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 179550.0,
    "priceUSD": 114.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 379,
    "name": "PANTALLA SOFT OLED - IPHONE 13 (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 151200.0,
    "priceUSD": 96.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 380,
    "name": "PANTALLA SOFT OLED - IPHONE 13 PRO (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 189000.0,
    "priceUSD": 120.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 381,
    "name": "PANTALLA SOFT OLED - IPHONE 13 PRO MAX 120 HZ (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 226800.0,
    "priceUSD": 144.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 382,
    "name": "PANTALLA SOFT OLED - IPHONE 14 (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 151200.0,
    "priceUSD": 96.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 383,
    "name": "PANTALLA SOFT OLED - IPHONE 14 PRO (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 330750.0,
    "priceUSD": 210.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 384,
    "name": "PANTALLA SOFT OLED - IPHONE 14 PRO MAX (ADMITE TRANSPLANTE IC)",
    "detail": "",
    "category": "Repuestos",
    "price": 368550.0,
    "priceUSD": 234.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 385,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE XR",
    "detail": "",
    "category": "Repuestos",
    "price": 37800.0,
    "priceUSD": 24.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 386,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE 11",
    "detail": "",
    "category": "Repuestos",
    "price": 47250.0,
    "priceUSD": 30.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 387,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE 11 PRO / 11 PRO MAX",
    "detail": "",
    "category": "Repuestos",
    "price": 92610.0,
    "priceUSD": 58.8,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 388,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE 12",
    "detail": "",
    "category": "Repuestos",
    "price": 66150.0,
    "priceUSD": 42.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 389,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE 12 MINI",
    "detail": "",
    "category": "Repuestos",
    "price": 85050.0,
    "priceUSD": 54.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  },
  {
    "id": 390,
    "name": "CAMARA TRASERA CALIDAD PREMIUM - IPHONE 12 PRO",
    "detail": "",
    "category": "Repuestos",
    "price": 189000.0,
    "priceUSD": 120.0,
    "stock": true,
    "comment": "",
    "icon": "🔧"
  }
];
